#include <gjs/vm/instruction.h>

namespace gjs {
    const char* instruction_str[(i32)vm_instruction::instruction_count] = {
        "null",
        "term",

        // memory
        "ld8",
        "ld16",
        "ld32",
        "ld64",
        "st8",
        "st16",
        "st32",
        "st64",
        "mptr",
        "mtfp",
        "mffp",

        // arithmetic
        "add",
        "addi",
        "sub",
        "subi",
        "subir",
        "mul",
        "muli",
        "div",
        "divi",
        "divir",

        // unsigned arithmetic
        "addu",
        "addui",
        "subu",
        "subui",
        "subuir",
        "mulu",
        "mului",
        "divu",
        "divui",
        "divuir",

        // integer / floating point conversion
        "cvt.i.f",
        "cvt.i.d",
        "cvt.i.u",
        "cvt.u.f",
        "cvt.u.d",
        "cvt.u.i",
        "cvt.f.i",
        "cvt.f.u",
        "cvt.f.d",
        "cvt.d.i",
        "cvt.d.u",
        "cvt.d.f",

        // floating point arithmetic
        "fadd",
        "faddi",
        "fsub",
        "fsubi",
        "fsubir",
        "fmul",
        "fmuli",
        "fdiv",
        "fdivi",
        "fdivir",
        "dadd",
        "daddi",
        "dsub",
        "dsubi",
        "dsubir",
        "dmul",
        "dmuli",
        "ddiv",
        "ddivi",
        "ddivir",

        // comparison
        "lt",
        "lti",
        "lte",
        "ltei",
        "gt",
        "gti",
        "gte",
        "gtei",
        "cmp",
        "cmpi",
        "ncmp",
        "ncmpi",
        
        // floating point comparison
        "flt",
        "flti",
        "flte",
        "fltei",
        "fgt",
        "fgti",
        "fgte",
        "fgtei",
        "fcmp",
        "fcmpi",
        "fncmp",
        "fncmpi",
        "dlt",
        "dlti",
        "dlte",
        "dltei",
        "dgt",
        "dgti",
        "dgte",
        "dgtei",
        "dcmp",
        "dcmpi",
        "dncmp",
        "dncmpi",

        // boolean
        "and",
        "andi",
        "or",
        "ori",

        // bitwise
        "band",
        "bandi",
        "bor",
        "bori",
        "xor",
        "xori",
        "sl",
        "sli",
        "slir",
        "sr",
        "sri",
        "srir",

        // control flow
        "beqz",
        "bneqz",
        "bgtz",
        "bgtez",
        "bltz",
        "bltez",
        "jmp",
        "jmpr",
        "jal",
        "jalr"
    };
};
